### ISSUE TITLE
Social WIfi training

### ISSUE THREAD

**Issue by omarinnsys** [innsysinternational/Business-Development#4]
guys What is the best timing for you?

Please be promote in your replies

**Comment by omarinnsys** [comment]
Mr. Mohamed is suggesting to have it on Saturday 1:00 pm

**Comment by ameerdirini** [comment]
I suggest that we conduct it as I suggested in the email which is 1:00 -3:00 pm

**Comment by omarinnsys** [comment]
I confirm
