### ISSUE TITLE
Demo for Fudds Rest

### ISSUE THREAD

**Issue by omarinnsys** [innsysinternational/Business-Development#5]
Prepare a PACTS PRO Demo that fits their business

**Comment by ameerdirini** [comment]
Omar, as I explained to you over the phone yesterday, I suggest that we conduct a working demo for Fudracker using Social-WiFis integrated with PACTSPRO. I have a demo for Fudruckers KSA which I can modify to Bahrain. I will work on modifying the Social-WiFis and integrate it with PACTSPRO demo that you will prepare on PACTSPRO.

**Comment by omarinnsys** [comment]
The demo has been done, and the proposals has been sent to 
Fuddruckers 
Caribou 
Marble Slab
